/**
 * qid 編號: 123
 * type 題型: 
 * ans 正確答案:
 * candidates 選項: 
 * sheet 卷別: 
 */

export default questions = [
  {
    qid: '1',
    type: 'YN',
    statement: '步測通常於中短距離使用。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '2',
    type: 'YN',
    statement: '衛兵攜槍姿勢，晝間持槍或提槍，夜間端槍或挾槍。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '3',
    type: 'YN',
    statement: '工事構築時，投土方法只有水平投土一種。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '甲',
  }, {
    qid: '4',
    type: 'YN',
    statement: '各種地形通過方法中，上坡為腳尖先著地。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '5',
    type: 'YN',
    statement: '步槍二十五公尺歸零涉及採用跪姿。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '甲',
  }, {
    qid: '6',
    type: 'YN',
    statement: '呼吸急促與微弱為熱中暑特有之現象。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '7',
    type: 'YN',
    statement: '躍進時，一次距離不超過二十公尺為宜。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '8',
    type: 'YN',
    statement: '夜間偽裝以人工材料塗黑並避免反光為原則。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '9',
    type: 'YN',
    statement: '目標距離的關係是目標小，距離遠，識別困難。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '10',
    type: 'YN',
    statement: '利用地形地物要領，守在發揚獲利，次在掩蔽身體。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '11',
    type: 'YN',
    statement: '於攻擊前進時應跟隨伍(班)同時前進，並各個交互躍進。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '12',
    type: 'YN',
    statement: '屋脊是一明顯稜線，最好避免利用。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '13',
    type: 'YN',
    statement: '樹幹鹿砦可選擇設置較薄弱處，爬月通過之。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '14',
    type: 'YN',
    statement: '依「毒品危害防制條例」之定義與分級，毒品共分四級。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '15',
    type: 'YN',
    statement: '地物利用中，小樹應利用根部，取跪姿，從右側射擊。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '甲',
  }, {
    qid: '16',
    type: 'YN',
    statement: '21世紀中國大陸經濟發展的最大挑戰為黨國不分。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '甲',
  }, {
    qid: '17',
    type: 'YN',
    statement: '進入長官寢室應先敲門並喊報告。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '18',
    type: 'YN',
    statement: '新兵受法院傳喚，依法院傳票，給予所需時日之公假。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '19',
    type: 'YN',
    statement: '夜間破壞鐵絲，是以隱密破壞為主。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '20',
    type: 'YN',
    statement: '肌腱反射減少為熱中暑特有之現象。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '21',
    type: 'SELECT',
    statement: '無[  ]之口令，任何人不能裝子彈。',
    candidates: [{ NO: '1', content: '旅長' }, { NO: '2', content: '營長' }, { NO: '3', content: '射擊指揮官' }],
    ans: { NO: '3', content: '射擊指揮官' },
    sheet: '甲',
  }, {
    qid: '22',
    type: 'SELECT',
    statement: '戰鬥忠言田埂運動時，應採[  ]。',
    candidates: [{ NO: '1', content: '潛行' }, { NO: '2', content: '爬行' }, { NO: '3', content: '側行' }],
    ans: { NO: '3', content: '側行' },
    sheet: '甲',
  }, {
    qid: '23',
    type: 'SELECT',
    statement: '構工前要先要求鄰冰掩護，裝滿子彈關保險後將槍至於[  ]。',
    candidates: [{ NO: '1', content: '下風處' }, { NO: '2', content: '上風處' }, { NO: '3', content: '以上皆非' }],
    ans: { NO: '2', content: '上風處' },
    sheet: '甲',
  }, {
    qid: '24',
    type: 'SELECT',
    statement: '聲光測，就是利用光速與[  ]之差來做依據。',
    candidates: [{ NO: '1', content: '距離' }, { NO: '2', content: '時間' }, { NO: '3', content: '音速' }],
    ans: { NO: '3', content: '音速' },
    sheet: '甲',
  }, {
    qid: '25',
    type: 'SELECT',
    statement: '對敵曲射武器隻掩蔽，利用下列何者為佳?',
    candidates: [{ NO: '1', content: '碉堡' }, { NO: '2', content: '彈坑' }, { NO: '3', content: '土堆' }],
    ans: { NO: '1', content: '碉堡' },
    sheet: '甲',
  }, {
    qid: '26',
    type: 'SELECT',
    statement: '裝子彈一律在[  ]實施。',
    candidates: [{ NO: '1', content: '待命線' }, { NO: '2', content: '射擊線' }, { NO: '3', content: '休息線' }],
    ans: { NO: '2', content: '射擊線' },
    sheet: '甲',
  }, {
    qid: '27',
    type: 'SELECT',
    statement: '夜間通過硬地[  ]。',
    candidates: [{ NO: '1', content: '腳尖先著地' }, { NO: '2', content: '腳跟先著地' }, { NO: '3', content: '腳尖腳跟同時著地' }],
    ans: { NO: '2', content: '腳跟先著地' },
    sheet: '甲',
  }, {
    qid: '28',
    type: 'SELECT',
    statement: '堆槍跑步槍身保持[  ]，兩臂順槍身軸線上下擺動。',
    candidates: [{ NO: '1', content: '二十度' }, { NO: '2', content: '三十度' }, { NO: '3', content: '四十五度' }],
    ans: { NO: '3', content: '四十五度' },
    sheet: '甲',
  }, {
    qid: '29',
    type: 'SELECT',
    statement: '現在戰爭的特性是[  ]，戰時軍需從事戰爭行動。',
    candidates: [{ NO: '1', content: '全體國民' }, { NO: '2', content: '全體國軍' }],
    ans: { NO: '1', content: '全體國民' },
    sheet: '甲',
  }, {
    qid: '30',
    type: 'SELECT',
    statement: '[  ]又名「促發熱」。',
    candidates: [{ NO: '1', content: '熱中暑' }, { NO: '2', content: '熱衰竭' }, { NO: '3', content: '熱痙攣' }],
    ans: { NO: '1', content: '熱中暑' },
    sheet: '甲',
  }, {
    qid: '31',
    type: 'SELECT',
    statement: '保密工作是具有[  ]。',
    candidates: [{ NO: '1', content: '強制性' }, { NO: '2', content: '約束性' }, { NO: '3', content: '以上皆是' }],
    ans: { NO: '3', content: '以上皆是' },
    sheet: '甲',
  }, {
    qid: '32',
    type: 'SELECT',
    statement: '碉堡因為不會移動所以稱為[  ]。',
    candidates: [{ NO: '1', content: '運動目標' }, { NO: '2', content: '固定目標' }, { NO: '3', content: '隱現目標' }],
    ans: { NO: '2', content: '固定目標' },
    sheet: '甲',
  }, {
    qid: '33',
    type: 'SELECT',
    statement: '軍人傳統武德為[  ]。',
    candidates: [{ NO: '1', content: '禮、義、廉、恥' }, { NO: '2', content: '忠、孝、仁、愛' }, { NO: '3', content: '智、信、仁、勇、嚴' }],
    ans: { NO: '3', content: '智、信、仁、勇、嚴' },
    sheet: '甲',
  }, {
    qid: '34',
    type: 'SELECT',
    statement: '單兵在戰場上最常用的距離測量方法為[  ]。',
    candidates: [{ NO: '1', content: '器械測' }, { NO: '2', content: '目測' }, { NO: '3', content: '繩測' }],
    ans: { NO: '2', content: '目測' },
    sheet: '甲',
  }, {
    qid: '35',
    type: 'SELECT',
    statement: '止血帶止血法運用於臂及手部，可縛於腋窩下[  ]。',
    candidates: [{ NO: '1', content: '五公分' }, { NO: '2', content: '十公分' }, { NO: '3', content: '十五公分' }],
    ans: { NO: '2', content: '十公分' },
    sheet: '甲',
  }, {
    qid: '36',
    type: 'SELECT',
    statement: '靶溝勤務人員非經[  ]同意不准離開。',
    candidates: [{ NO: '1', content: '營長' }, { NO: '2', content: '連長' }, { NO: '3', content: '射擊指揮官' }],
    ans: { NO: '3', content: '射擊指揮官' },
    sheet: '甲',
  }, {
    qid: '37',
    type: 'SELECT',
    statement: '地表面平坦的地區為[  ]。',
    candidates: [{ NO: '1', content: '平原' }, { NO: '2', content: '平地' }, { NO: '3', content: '開闊地' }],
    ans: { NO: '2', content: '平地' },
    sheet: '甲',
  }, {
    qid: '38',
    type: 'SELECT',
    statement: '箱上瞄準右眼位於覘孔直後方約[  ]處。',
    candidates: [{ NO: '1', content: '十公分' }, { NO: '2', content: '十五公分' }, { NO: '3', content: '五公分' }],
    ans: { NO: '1', content: '十公分' },
    sheet: '甲',
  }, {
    qid: '39',
    type: 'SELECT',
    statement: '地表上的形狀形成高低起伏的狀態稱為[  ]。',
    candidates: [{ NO: '1', content: '地形' }, { NO: '2', content: '地物' }, { NO: '3', content: '地貌' }],
    ans: { NO: '3', content: '地貌' },
    sheet: '甲',
  }, {
    qid: '40',
    type: 'SELECT',
    statement: '夜間通過軟地時，應[  ]著地。',
    candidates: [{ NO: '1', content: '腳尖' }, { NO: '2', content: '腳跟' }, { NO: '3', content: '腳尖與腳跟同時' }],
    ans: { NO: '1', content: '腳尖' },
    sheet: '甲',
  },

  // 乙卷

  {
    qid: '41',
    type: 'YN',
    statement: '兩岸關係最不穩定因素為中共始終不放棄武力犯台。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '42',
    type: 'YN',
    statement: '偽裝軍紀以不破壞現地自然景況。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '43',
    type: 'YN',
    statement: '正確瞄準圖係將覘孔、準星、目標所構成之正確關係。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '44',
    type: 'YN',
    statement: '所謂三戰即為輿論戰、心理戰及法律戰。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '45',
    type: 'YN',
    statement: '軍人傳統武德為「智、信、仁、勇、嚴」。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '46',
    type: 'YN',
    statement: '偽裝時須注意變更偽裝物之型態、陰影，但不必注意線條與顏色。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '乙',
  }, {
    qid: '47',
    type: 'YN',
    statement: '聞取槍口令時，各基準兵以左手握持槍位置，雙眼仍注視前方。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '乙',
  }, {
    qid: '48',
    type: 'YN',
    statement: '積土的厚度，胸牆至少需一公尺。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '49',
    type: 'YN',
    statement: '夜間偵聽時最好閉口，並暫時停止呼吸。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '乙',
  }, {
    qid: '50',
    type: 'YN',
    statement: '通過不平地時，應將腳提高，腳掌慢慢著地。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '51',
    type: 'YN',
    statement: '「反分裂國家法」為中共反制台灣向外發展的一條法律戰線。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '52',
    type: 'YN',
    statement: '我國現階段台澎防衛作戰的戰略指導為「有效嚇阻，防衛固守」。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '53',
    type: 'YN',
    statement: '地形就是地表面上的形狀，包括地貌地物。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '54',
    type: 'YN',
    statement: '射擊位置如遭敵射擊，應加強偽裝。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '乙',
  }, {
    qid: '55',
    type: 'YN',
    statement: '凡軍中一切與軍事有關之物品均是軍用品。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '56',
    type: 'YN',
    statement: '小十字鎬它的功用在戰鬥中可以當無聲武器之用。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '57',
    type: 'YN',
    statement: '施用第一級毒品，處三年以下有期徒刑。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '乙',
  }, {
    qid: '58',
    type: 'YN',
    statement: '各種工事之經始，首應按其射擊方向或區域，選定其方向線。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '59',
    type: 'YN',
    statement: '立正時，兩腳靠攏並齊，腳尖向外分開四十度。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '乙',
  }, {
    qid: '60',
    type: 'YN',
    statement: '工事位置力求分散，火力力求集中。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  },

]