/**
 * qid 編號: 123
 * type 題型: 
 * ans 正確答案:
 * candidates 選項: 
 * sheet 卷別: 
 */

export default questions = [
  {
    qid: '1',
    type: 'YN',
    statement: '步測通常於中短距離使用。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '2',
    type: 'YN',
    statement: '衛兵攜槍姿勢，晝間持槍或提槍，夜間端槍或挾槍。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '3',
    type: 'YN',
    statement: '工事構築時，投土方法只有水平投土一種。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '甲',
  }, {
    qid: '4',
    type: 'YN',
    statement: '各種地形通過方法中，上坡為腳尖先著地。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '5',
    type: 'YN',
    statement: '步槍二十五公尺歸零涉及採用跪姿。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '甲',
  }, {
    qid: '6',
    type: 'YN',
    statement: '呼吸急促與微弱為熱中暑特有之現象。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '7',
    type: 'YN',
    statement: '躍進時，一次距離不超過二十公尺為宜。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '8',
    type: 'YN',
    statement: '夜間偽裝以人工材料塗黑並避免反光為原則。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '9',
    type: 'YN',
    statement: '目標距離的關係是目標小，距離遠，識別困難。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '10',
    type: 'YN',
    statement: '利用地形地物要領，守在發揚獲利，次在掩蔽身體。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '11',
    type: 'YN',
    statement: '於攻擊前進時應跟隨伍(班)同時前進，並各個交互躍進。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '12',
    type: 'YN',
    statement: '屋脊是一明顯稜線，最好避免利用。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '13',
    type: 'YN',
    statement: '樹幹鹿砦可選擇設置較薄弱處，爬月通過之。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '14',
    type: 'YN',
    statement: '依「毒品危害防制條例」之定義與分級，毒品共分四級。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '15',
    type: 'YN',
    statement: '地物利用中，小樹應利用根部，取跪姿，從右側射擊。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '甲',
  }, {
    qid: '16',
    type: 'YN',
    statement: '21世紀中國大陸經濟發展的最大挑戰為黨國不分。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '甲',
  }, {
    qid: '17',
    type: 'YN',
    statement: '進入長官寢室應先敲門並喊報告。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '18',
    type: 'YN',
    statement: '新兵受法院傳喚，依法院傳票，給予所需時日之公假。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '19',
    type: 'YN',
    statement: '夜間破壞鐵絲，是以隱密破壞為主。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '20',
    type: 'YN',
    statement: '肌腱反射減少為熱中暑特有之現象。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '甲',
  }, {
    qid: '21',
    type: 'SELECT',
    statement: '無[  ]之口令，任何人不能裝子彈。',
    candidates: [{ NO: '1', content: '旅長' }, { NO: '2', content: '營長' }, { NO: '3', content: '射擊指揮官' }],
    ans: { NO: '3', content: '射擊指揮官' },
    sheet: '甲',
  }, {
    qid: '22',
    type: 'SELECT',
    statement: '戰鬥忠言田埂運動時，應採[  ]。',
    candidates: [{ NO: '1', content: '潛行' }, { NO: '2', content: '爬行' }, { NO: '3', content: '側行' }],
    ans: { NO: '3', content: '側行' },
    sheet: '甲',
  }, {
    qid: '23',
    type: 'SELECT',
    statement: '構工前要先要求鄰冰掩護，裝滿子彈關保險後將槍至於[  ]。',
    candidates: [{ NO: '1', content: '下風處' }, { NO: '2', content: '上風處' }, { NO: '3', content: '以上皆非' }],
    ans: { NO: '2', content: '上風處' },
    sheet: '甲',
  }, {
    qid: '24',
    type: 'SELECT',
    statement: '聲光測，就是利用光速與[  ]之差來做依據。',
    candidates: [{ NO: '1', content: '距離' }, { NO: '2', content: '時間' }, { NO: '3', content: '音速' }],
    ans: { NO: '3', content: '音速' },
    sheet: '甲',
  }, {
    qid: '25',
    type: 'SELECT',
    statement: '對敵曲射武器隻掩蔽，利用下列何者為佳?',
    candidates: [{ NO: '1', content: '碉堡' }, { NO: '2', content: '彈坑' }, { NO: '3', content: '土堆' }],
    ans: { NO: '1', content: '碉堡' },
    sheet: '甲',
  }, {
    qid: '26',
    type: 'SELECT',
    statement: '裝子彈一律在[  ]實施。',
    candidates: [{ NO: '1', content: '待命線' }, { NO: '2', content: '射擊線' }, { NO: '3', content: '休息線' }],
    ans: { NO: '2', content: '射擊線' },
    sheet: '甲',
  }, {
    qid: '27',
    type: 'SELECT',
    statement: '夜間通過硬地[  ]。',
    candidates: [{ NO: '1', content: '腳尖先著地' }, { NO: '2', content: '腳跟先著地' }, { NO: '3', content: '腳尖腳跟同時著地' }],
    ans: { NO: '2', content: '腳跟先著地' },
    sheet: '甲',
  }, {
    qid: '28',
    type: 'SELECT',
    statement: '堆槍跑步槍身保持[  ]，兩臂順槍身軸線上下擺動。',
    candidates: [{ NO: '1', content: '二十度' }, { NO: '2', content: '三十度' }, { NO: '3', content: '四十五度' }],
    ans: { NO: '3', content: '四十五度' },
    sheet: '甲',
  }, {
    qid: '29',
    type: 'SELECT',
    statement: '現在戰爭的特性是[  ]，戰時軍需從事戰爭行動。',
    candidates: [{ NO: '1', content: '全體國民' }, { NO: '2', content: '全體國軍' }],
    ans: { NO: '1', content: '全體國民' },
    sheet: '甲',
  }, {
    qid: '30',
    type: 'SELECT',
    statement: '[  ]又名「促發熱」。',
    candidates: [{ NO: '1', content: '熱中暑' }, { NO: '2', content: '熱衰竭' }, { NO: '3', content: '熱痙攣' }],
    ans: { NO: '1', content: '熱中暑' },
    sheet: '甲',
  }, {
    qid: '31',
    type: 'SELECT',
    statement: '保密工作是具有[  ]。',
    candidates: [{ NO: '1', content: '強制性' }, { NO: '2', content: '約束性' }, { NO: '3', content: '以上皆是' }],
    ans: { NO: '3', content: '以上皆是' },
    sheet: '甲',
  }, {
    qid: '32',
    type: 'SELECT',
    statement: '碉堡因為不會移動所以稱為[  ]。',
    candidates: [{ NO: '1', content: '運動目標' }, { NO: '2', content: '固定目標' }, { NO: '3', content: '隱現目標' }],
    ans: { NO: '2', content: '固定目標' },
    sheet: '甲',
  }, {
    qid: '33',
    type: 'SELECT',
    statement: '軍人傳統武德為[  ]。',
    candidates: [{ NO: '1', content: '禮、義、廉、恥' }, { NO: '2', content: '忠、孝、仁、愛' }, { NO: '3', content: '智、信、仁、勇、嚴' }],
    ans: { NO: '3', content: '智、信、仁、勇、嚴' },
    sheet: '甲',
  }, {
    qid: '34',
    type: 'SELECT',
    statement: '單兵在戰場上最常用的距離測量方法為[  ]。',
    candidates: [{ NO: '1', content: '器械測' }, { NO: '2', content: '目測' }, { NO: '3', content: '繩測' }],
    ans: { NO: '2', content: '目測' },
    sheet: '甲',
  }, {
    qid: '35',
    type: 'SELECT',
    statement: '止血帶止血法運用於臂及手部，可縛於腋窩下[  ]。',
    candidates: [{ NO: '1', content: '五公分' }, { NO: '2', content: '十公分' }, { NO: '3', content: '十五公分' }],
    ans: { NO: '2', content: '十公分' },
    sheet: '甲',
  }, {
    qid: '36',
    type: 'SELECT',
    statement: '靶溝勤務人員非經[  ]同意不准離開。',
    candidates: [{ NO: '1', content: '營長' }, { NO: '2', content: '連長' }, { NO: '3', content: '射擊指揮官' }],
    ans: { NO: '3', content: '射擊指揮官' },
    sheet: '甲',
  }, {
    qid: '37',
    type: 'SELECT',
    statement: '地表面平坦的地區為[  ]。',
    candidates: [{ NO: '1', content: '平原' }, { NO: '2', content: '平地' }, { NO: '3', content: '開闊地' }],
    ans: { NO: '2', content: '平地' },
    sheet: '甲',
  }, {
    qid: '38',
    type: 'SELECT',
    statement: '箱上瞄準右眼位於覘孔直後方約[  ]處。',
    candidates: [{ NO: '1', content: '十公分' }, { NO: '2', content: '十五公分' }, { NO: '3', content: '五公分' }],
    ans: { NO: '1', content: '十公分' },
    sheet: '甲',
  }, {
    qid: '39',
    type: 'SELECT',
    statement: '地表上的形狀形成高低起伏的狀態稱為[  ]。',
    candidates: [{ NO: '1', content: '地形' }, { NO: '2', content: '地物' }, { NO: '3', content: '地貌' }],
    ans: { NO: '3', content: '地貌' },
    sheet: '甲',
  }, {
    qid: '40',
    type: 'SELECT',
    statement: '夜間通過軟地時，應[  ]著地。',
    candidates: [{ NO: '1', content: '腳尖' }, { NO: '2', content: '腳跟' }, { NO: '3', content: '腳尖與腳跟同時' }],
    ans: { NO: '1', content: '腳尖' },
    sheet: '甲',
  },

  // 乙卷

  {
    qid: '41',
    type: 'YN',
    statement: '兩岸關係最不穩定因素為中共始終不放棄武力犯台。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '42',
    type: 'YN',
    statement: '偽裝軍紀以不破壞現地自然景況。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '43',
    type: 'YN',
    statement: '正確瞄準圖係將覘孔、準星、目標所構成之正確關係。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '44',
    type: 'YN',
    statement: '所謂三戰即為輿論戰、心理戰及法律戰。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '45',
    type: 'YN',
    statement: '軍人傳統武德為「智、信、仁、勇、嚴」。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '46',
    type: 'YN',
    statement: '偽裝時須注意變更偽裝物之型態、陰影，但不必注意線條與顏色。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '乙',
  }, {
    qid: '47',
    type: 'YN',
    statement: '聞取槍口令時，各基準兵以左手握持槍位置，雙眼仍注視前方。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '乙',
  }, {
    qid: '48',
    type: 'YN',
    statement: '積土的厚度，胸牆至少需一公尺。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '49',
    type: 'YN',
    statement: '夜間偵聽時最好閉口，並暫時停止呼吸。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '乙',
  }, {
    qid: '50',
    type: 'YN',
    statement: '通過不平地時，應將腳提高，腳掌慢慢著地。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '51',
    type: 'YN',
    statement: '「反分裂國家法」為中共反制台灣向外發展的一條法律戰線。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '52',
    type: 'YN',
    statement: '我國現階段台澎防衛作戰的戰略指導為「有效嚇阻，防衛固守」。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '53',
    type: 'YN',
    statement: '地形就是地表面上的形狀，包括地貌地物。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '54',
    type: 'YN',
    statement: '射擊位置如遭敵射擊，應加強偽裝。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '乙',
  }, {
    qid: '55',
    type: 'YN',
    statement: '凡軍中一切與軍事有關之物品均是軍用品。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '56',
    type: 'YN',
    statement: '小十字鎬它的功用在戰鬥中可以當無聲武器之用。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '57',
    type: 'YN',
    statement: '施用第一級毒品，處三年以下有期徒刑。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '乙',
  }, {
    qid: '58',
    type: 'YN',
    statement: '各種工事之經始，首應按其射擊方向或區域，選定其方向線。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '59',
    type: 'YN',
    statement: '立正時，兩腳靠攏並齊，腳尖向外分開四十度。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '乙',
  }, {
    qid: '60',
    type: 'YN',
    statement: '工事位置力求分散，火力力求集中。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '乙',
  }, {
    qid: '61',
    type: 'SELECT',
    statement: '熱中暑先兆症狀，下列何者為非?',
    candidates: [{ NO: '1', content: '畏寒起雞皮疙瘩' }, { NO: '2', content: '噁心嘔吐' }, { NO: '3', content: '皮膚濕冷' }],
    ans: { NO: '3', content: '皮膚濕冷' },
    sheet: '乙',
  }, {
    qid: '62',
    type: 'SELECT',
    statement: '六五式K2步槍之有效射程為[  ]公尺。',
    candidates: [{ NO: '1', content: '500' }, { NO: '2', content: '550' }, { NO: '3', content: '600' }],
    ans: { NO: '3', content: '600' },
    sheet: '乙',
  }, {
    qid: '63',
    type: 'SELECT',
    statement: '衛兵通常以[  ]換班一次。',
    candidates: [{ NO: '1', content: '三小時' }, { NO: '2', content: '兩小時' }, { NO: '3', content: '一小時' }],
    ans: { NO: '2', content: '兩小時' },
    sheet: '乙',
  }, {
    qid: '64',
    type: 'SELECT',
    statement: '因素在空氣中，每秒約[  ]。',
    candidates: [{ NO: '1', content: '333公尺' }, { NO: '2', content: '500公尺' }, { NO: '3', content: '1000公尺' }],
    ans: { NO: '1', content: '333公尺' },
    sheet: '乙',
  }, {
    qid: '65',
    type: 'SELECT',
    statement: '偵聽時最好要張開口並且[  ]。',
    candidates: [{ NO: '1', content: '暫停呼吸' }, { NO: '2', content: '深呼吸' }, { NO: '3', content: '無所謂' }],
    ans: { NO: '1', content: '暫停呼吸' },
    sheet: '乙',
  }, {
    qid: '66',
    type: 'SELECT',
    statement: '憲法第[  ]條為「任何黨派及個人不得以武裝力量為政爭工具。」',
    candidates: [{ NO: '1', content: '138' }, { NO: '2', content: '139' }, { NO: '3', content: '140' }],
    ans: { NO: '2', content: '139' },
    sheet: '乙',
  }, {
    qid: '67',
    type: 'SELECT',
    statement: '實距離歸零射擊，修正表尺，報表方式[  ]。',
    candidates: [{ NO: '1', content: '一發一報' }, { NO: '2', content: '二發一報' }, { NO: '3', content: '一發二報' }],
    ans: { NO: '1', content: '一發一報' },
    sheet: '乙',
  }, {
    qid: '68',
    type: 'SELECT',
    statement: '公路為寬在[  ]公尺以上，可通行車輛的道路。',
    candidates: [{ NO: '1', content: '三' }, { NO: '2', content: '四' }, { NO: '3', content: '五' }],
    ans: { NO: '2', content: '四' },
    sheet: '乙',
  }, {
    qid: '69',
    type: 'SELECT',
    statement: '對有直屬關係之上官應先呼[  ]再稱其職。',
    candidates: [{ NO: '1', content: '姓氏' }, { NO: '2', content: '好' }, { NO: '3', content: '報告' }],
    ans: { NO: '3', content: '報告' },
    sheet: '乙',
  }, {
    qid: '70',
    type: 'SELECT',
    statement: '[  ]將撼動中國共產黨的執政基礎。',
    candidates: [{ NO: '1', content: '經濟衰退' }, { NO: '2', content: '社會不穩定的危機' }, { NO: '3', content: '戰爭' }],
    ans: { NO: '2', content: '社會不穩定的危機' },
    sheet: '乙',
  }, {
    qid: '71',
    type: 'SELECT',
    statement: '跪射散兵坑胸牆基土高約[  ]。',
    candidates: [{ NO: '1', content: '五十公分' }, { NO: '2', content: '四十公分' }, { NO: '3', content: '三十公分' }],
    ans: { NO: '3', content: '三十公分' },
    sheet: '乙',
  }, {
    qid: '72',
    type: 'SELECT',
    statement: '用槍姿勢聞「停」口令，[  ]。',
    candidates: [{ NO: '1', content: '左腳後收向右腳靠攏' }, { NO: '2', content: '無規定' }, { NO: '3', content: '右腳上步向左腳靠攏' }],
    ans: { NO: '3', content: '右腳上步向左腳靠攏' },
    sheet: '乙',
  }, {
    qid: '73',
    type: 'SELECT',
    statement: '掩護要領之一是[  ]。',
    candidates: [{ NO: '1', content: '動的掩護不動的' }, { NO: '2', content: '不動掩護動的' }, { NO: '3', content: '以上皆是' }],
    ans: { NO: '2', content: '不動掩護動的' },
    sheet: '乙',
  }, {
    qid: '74',
    type: 'SELECT',
    statement: '宣傳的方式有口頭宣傳，文字宣傳和[  ]。',
    candidates: [{ NO: '1', content: '行動宣傳' }, { NO: '2', content: '報導宣傳' }, { NO: '3', content: '海報宣傳' }],
    ans: { NO: '1', content: '行動宣傳' },
    sheet: '乙',
  }, {
    qid: '75',
    type: 'SELECT',
    statement: '21世紀中國大陸經濟發展的最大挑戰為',
    candidates: [{ NO: '1', content: '貪污' }, { NO: '2', content: '黨國不分' }, { NO: '3', content: '分配不均' }],
    ans: { NO: '3', content: '分配不均' },
    sheet: '乙',
  }, {
    qid: '76',
    type: 'SELECT',
    statement: '新兵訓練175公尺鑑定涉及採何者姿勢?',
    candidates: [{ NO: '1', content: '跪姿' }, { NO: '2', content: '立姿' }, { NO: '3', content: '臥姿' }],
    ans: { NO: '3', content: '臥姿' },
    sheet: '乙',
  }, {
    qid: '77',
    type: 'SELECT',
    statement: '進入射擊場首先要[  ]。',
    candidates: [{ NO: '1', content: '扣板機' }, { NO: '2', content: '開保險' }, { NO: '3', content: '驗槍' }],
    ans: { NO: '3', content: '驗槍' },
    sheet: '乙',
  }, {
    qid: '78',
    type: 'SELECT',
    statement: '核爆威力中，核輻射佔全部威力的百分之[  ]。',
    candidates: [{ NO: '1', content: '十五' }, { NO: '2', content: '三十五' }, { NO: '3', content: '五十' }],
    ans: { NO: '1', content: '十五' },
    sheet: '乙',
  }, {
    qid: '79',
    type: 'SELECT',
    statement: '感染神經毒劑時，應使用何者治療?',
    candidates: [{ NO: '1', content: '六五式防護包' }, { NO: '2', content: '神經毒劑解毒針' }, { NO: '3', content: '亞硝酸戊脂' }],
    ans: { NO: '2', content: '神經毒劑解毒針' },
    sheet: '乙',
  }, {
    qid: '80',
    type: 'SELECT',
    statement: '偵查回報時，報告內容通常包括何人，何時，何地，何事及[  ]。',
    candidates: [{ NO: '1', content: '如何' }, { NO: '2', content: '為何' }, { NO: '3', content: '何物' }],
    ans: { NO: '1', content: '如何' },
    sheet: '乙',
  },

  // 丙卷

  {
    qid: '81',
    type: 'YN',
    statement: '劃經始時，第一動為決定AB首線。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '丙',
  }, {
    qid: '82',
    type: 'YN',
    statement: '複雜地因地形開闊，故搜索、聯絡、掌握均很容易。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '丙',
  }, {
    qid: '83',
    type: 'YN',
    statement: '射擊位置的選擇首要在便於聯絡及進出容易。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '丙',
  }, {
    qid: '84',
    type: 'YN',
    statement: '地形開闊平坦，目標無背景時，識別困難。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '丙',
  }, {
    qid: '85',
    type: 'YN',
    statement: '凹形斜坡地形等高線高密低疏。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '丙',
  }, {
    qid: '86',
    type: 'YN',
    statement: '暈眩、軟弱無力為虛脫現象，稍事休息即可。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '丙',
  }, {
    qid: '87',
    type: 'YN',
    statement: '身體發冷、出汗異常增多為中暑現象。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '丙',
  }, {
    qid: '88',
    type: 'YN',
    statement: '人、事、時、地為調查的主要對象。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '丙',
  }, {
    qid: '89',
    type: 'YN',
    statement: '分化團結係指一個人的語言、態度、行動及精神，違反常理。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '丙',
  }, {
    qid: '90',
    type: 'YN',
    statement: '山腹式山頂與山脊之間的斜面部分。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '丙',
  }, {
    qid: '91',
    type: 'YN',
    statement: '防毒面具清洗時，不可用有機溶劑洗刷。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '丙',
  }, {
    qid: '92',
    type: 'YN',
    statement: '衛兵職責以軍紀及安全為主。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '丙',
  }, {
    qid: '93',
    type: 'YN',
    statement: '國軍「軍人信念」為「國家、責任、榮譽」。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '丙',
  }, {
    qid: '94',
    type: 'YN',
    statement: '裝具攜行，應配戴確實，而俺光的物品，為求安全，均不得攜帶。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '丙',
  }, {
    qid: '95',
    type: 'YN',
    statement: '稍息時，左腳向左橫移四十五公分。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '丙',
  }, {
    qid: '96',
    type: 'YN',
    statement: '輔導訴訟的對象，以現役軍人及軍眷為限。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '丙',
  }, {
    qid: '97',
    type: 'YN',
    statement: '新兵參加高普考須請事假，不得利用公家時間。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '丙',
  }, {
    qid: '98',
    type: 'YN',
    statement: '夜間障礙物破壞後不需加以標示。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '丙',
  }, {
    qid: '99',
    type: 'YN',
    statement: '指北針磁感應距離高壓電線為三十公尺。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '丙',
  }, {
    qid: '100',
    type: 'YN',
    statement: '乘坐大卡車時，應按順序兩邊坐好，如沒有座位，可站立於車中。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '丙',
  }, {
    qid: '101',
    type: 'SELECT',
    statement: '入室後，距長官適當距離[  ]處立正。',
    candidates: [{ NO: '1', content: '約一步' }, { NO: '2', content: '約三至五步' }, { NO: '3', content: '約十步' }],
    ans: { NO: '2', content: '約三至五步' },
    sheet: '丙',
  }, {
    qid: '102',
    type: 'SELECT',
    statement: '掩護要領之一是[  ]。',
    candidates: [{ NO: '1', content: '動的掩護不動的' }, { NO: '2', content: '不動掩護動的' }, { NO: '3', content: '以上皆是' }],
    ans: { NO: '2', content: '不動掩護動的' },
    sheet: '丙',
  }, {
    qid: '103',
    type: 'SELECT',
    statement: '單人立射散兵坑可分[  ]，以上何者為非?',
    candidates: [{ NO: '1', content: '開置式' }, { NO: '2', content: '封閉式' }, { NO: '3', content: '半掩蓋式' }],
    ans: { NO: '2', content: '封閉式' },
    sheet: '丙',
  }, {
    qid: '104',
    type: 'SELECT',
    statement: '中共對台政治工作手段，長期以來，皆以[  ]為原則。',
    candidates: [{ NO: '1', content: '一個中國' }, { NO: '2', content: '一國兩制' }, { NO: '3', content: '和平統一' }],
    ans: { NO: '1', content: '一個中國' },
    sheet: '丙',
  }, {
    qid: '105',
    type: 'SELECT',
    statement: '運動時不得[  ]。',
    candidates: [{ NO: '1', content: '妨礙鄰兵射擊' }, { NO: '2', content: '橫方向移動' }, { NO: '3', content: '以上皆是' }],
    ans: { NO: '3', content: '以上皆是' },
    sheet: '丙',
  }, {
    qid: '106',
    type: 'SELECT',
    statement: '對固定目標偵查，首先要[  ]。',
    candidates: [{ NO: '1', content: '尋找目標的位置' }, { NO: '2', content: '記憶目標位置' }, { NO: '3', content: '測量自己置目標間的距離' }],
    ans: { NO: '1', content: '尋找目標的位置' },
    sheet: '丙',
  }, {
    qid: '107',
    type: 'SELECT',
    statement: '持槍敬禮時，左手小臂向右彎[  ]，小臂保持水平。',
    candidates: [{ NO: '1', content: '三十度' }, { NO: '2', content: '六十度' }, { NO: '3', content: '九十度' }],
    ans: { NO: '3', content: '九十度' },
    sheet: '丙',
  }, {
    qid: '108',
    type: 'SELECT',
    statement: '[  ]對攻防兩者隱(掩)蔽均良好',
    candidates: [{ NO: '1', content: '開闊地' }, { NO: '2', content: '複雜地' }, { NO: '3', content: '森林' }],
    ans: { NO: '3', content: '森林' },
    sheet: '丙',
  }, {
    qid: '109',
    type: 'SELECT',
    statement: '夜間眾人通過鐵絲網時，一人先行[  ]破壞通過。',
    candidates: [{ NO: '1', content: '仰臥' }, { NO: '2', content: '伏臥' }, { NO: '3', content: '躺臥' }],
    ans: { NO: '1', content: '仰臥' },
    sheet: '丙',
  }, {
    qid: '110',
    type: 'SELECT',
    statement: '橋梁依照橋的材料分，可分為[  ]種',
    candidates: [{ NO: '1', content: '三' }, { NO: '2', content: '四' }, { NO: '3', content: '五' }],
    ans: { NO: '2', content: '四' },
    sheet: '丙',
  }, {
    qid: '111',
    type: 'SELECT',
    statement: '軍愛民的具體行為是[  ]。',
    candidates: [{ NO: '1', content: '用民' }, { NO: '2', content: '助民' }, { NO: '3', content: '以上皆是' }],
    ans: { NO: '2', content: '助民' },
    sheet: '丙',
  }, {
    qid: '112',
    type: 'SELECT',
    statement: '保密工作是具有[  ]。',
    candidates: [{ NO: '1', content: '強制性' }, { NO: '2', content: '約束性' }, { NO: '3', content: '以上皆是' }],
    ans: { NO: '3', content: '以上皆是' },
    sheet: '丙',
  }, {
    qid: '113',
    type: 'SELECT',
    statement: '夜間單兵戰鬥著裝要領為[  ]。',
    candidates: [{ NO: '1', content: '整齊清潔' }, { NO: '2', content: '迅速光潔' }, { NO: '3', content: '沉著靜肅' }],
    ans: { NO: '3', content: '沉著靜肅' },
    sheet: '丙',
  }, {
    qid: '114',
    type: 'SELECT',
    statement: '小圓鍬全長[  ]。',
    candidates: [{ NO: '1', content: '五十公分' }, { NO: '2', content: '六十公分' }, { NO: '3', content: '七十公分' }],
    ans: { NO: '2', content: '六十公分' },
    sheet: '丙',
  }, {
    qid: '115',
    type: 'SELECT',
    statement: '聞稍息口令時，左腳向左橫移[  ]',
    candidates: [{ NO: '1', content: '三十公分' }, { NO: '2', content: '六十公分' }, { NO: '3', content: '九十公分' }],
    ans: { NO: '1', content: '三十公分' },
    sheet: '丙',
  }, {
    qid: '116',
    type: 'SELECT',
    statement: '射擊位置的選擇首在[  ]。',
    candidates: [{ NO: '1', content: '便於聯絡及進出' }, { NO: '2', content: '發揚火力' }, { NO: '3', content: '以上皆可' }],
    ans: { NO: '2', content: '發揚火力' },
    sheet: '丙',
  }, {
    qid: '117',
    type: 'SELECT',
    statement: '瞄準模型具練習其距離為[  ]。',
    candidates: [{ NO: '1', content: '十公尺' }, { NO: '2', content: '十五公尺' }, { NO: '3', content: '三十公尺' }],
    ans: { NO: '2', content: '十五公尺' },
    sheet: '丙',
  }, {
    qid: '118',
    type: 'SELECT',
    statement: '施打(服用)第2級毒品需處[  ]年以下有期徒刑。',
    candidates: [{ NO: '1', content: '三' }, { NO: '2', content: '二' }, { NO: '3', content: '一' }],
    ans: { NO: '1', content: '三' },
    sheet: '丙',
  }, {
    qid: '119',
    type: 'SELECT',
    statement: '門窗為良好之射擊位置，通常利用門窗之[  ]。',
    candidates: [{ NO: '1', content: '左側' }, { NO: '2', content: '右側' }, { NO: '3', content: '以上皆是' }],
    ans: { NO: '1', content: '左側' },
    sheet: '丙',
  }, {
    qid: '120',
    type: 'SELECT',
    statement: '槍枝如於射擊中故障，[  ]。',
    candidates: [{ NO: '1', content: '自行排除' }, { NO: '2', content: '助教監督排除' }, { NO: '3', content: '換一把' }],
    ans: { NO: '2', content: '助教監督排除' },
    sheet: '丙',
  },

  // 丁卷

  {
    qid: '121',
    type: 'YN',
    statement: '射擊位置的選擇通常利用掩蔽物左側。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '丁',
  }, {
    qid: '122',
    type: 'YN',
    statement: '鋼盔偽裝時，可用泥土將鋼盔塗成規則形狀。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '丁',
  }, {
    qid: '123',
    type: 'YN',
    statement: '所謂地物，就是地球表面上固定性物體，包括天然或人為物體。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '丁',
  }, {
    qid: '124',
    type: 'YN',
    statement: '箱上瞄準時，兩箱距離為十二公尺。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '丁',
  }, {
    qid: '125',
    type: 'YN',
    statement: '碉堡、坑道、防空洞等對敵曲射兵器的掩蔽較為有效。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '丁',
  }, {
    qid: '126',
    type: 'YN',
    statement: '徐徐扣引板機，為據槍要領中最重要的一環。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '丁',
  }, {
    qid: '127',
    type: 'YN',
    statement: '構築工事完成後，再實施偽裝。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '丁',
  }, {
    qid: '128',
    type: 'YN',
    statement: '哨兵之任務以執行監護警戒及特定任務為主。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '丁',
  }, {
    qid: '129',
    type: 'YN',
    statement: '偵查位置的選定，於防禦時多由班(伍)長指示。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '丁',
  }, {
    qid: '130',
    type: 'YN',
    statement: '仰臥起坐在鍛練腰部，增強體力與腹肌力。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '丁',
  }, {
    qid: '131',
    type: 'YN',
    statement: '夜間突然出現之隱現目標，一避眼一至二秒再偵查。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '丁',
  }, {
    qid: '132',
    type: 'YN',
    statement: '刺槍術須達到「快、狠、準、猛」，練成「氣、刀、體」一致之精神。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '丁',
  }, {
    qid: '133',
    type: 'YN',
    statement: '夜間通過叢林與高莖作物，先用手將樹枝及高莖作物分開再前進。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '丁',
  }, {
    qid: '134',
    type: 'YN',
    statement: '土坑、壕溝、建築物等對敵曲射兵器的掩避較為有效。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '丁',
  }, {
    qid: '135',
    type: 'YN',
    statement: '水流速度每秒五公尺以上稱為急流。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '丁',
  }, {
    qid: '136',
    type: 'YN',
    statement: '偽裝乃利用地形地物或人工設施，求得自己隱匿與遮蔽。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '丁',
  }, {
    qid: '137',
    type: 'YN',
    statement: '如無彈坑又無地形可利用時，就需構築急迫掩體。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '丁',
  }, {
    qid: '138',
    type: 'YN',
    statement: '火箭筒後方要有30公尺安全距離。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '丁',
  }, {
    qid: '139',
    type: 'YN',
    statement: '道路為部隊運動、後勤支援、戰術運用不可或缺之要件。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '丁',
  }, {
    qid: '140',
    type: 'YN',
    statement: '步槍射擊停止呼吸，每次時間以不超過十秒鐘為宜。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '丁',
  }, {
    qid: '141',
    type: 'SELECT',
    statement: '何者不是據槍要領?',
    candidates: [{ NO: '1', content: '瞄' }, { NO: '2', content: '托' }, { NO: '3', content: '推' }],
    ans: { NO: '3', content: '推' },
    sheet: '丁',
  }, {
    qid: '142',
    type: 'SELECT',
    statement: '下列何者為第一級毒品?',
    candidates: [{ NO: '1', content: '大麻' }, { NO: '2', content: '海洛因' }, { NO: '3', content: '安非他命' }],
    ans: { NO: '2', content: '海洛因' },
    sheet: '丁',
  }, {
    qid: '143',
    type: 'SELECT',
    statement: '地形地物運用要領為[  ]。',
    candidates: [{ NO: '1', content: '發揚火力' }, { NO: '2', content: '掩避身體' }, { NO: '3', content: '以上皆是' }],
    ans: { NO: '3', content: '以上皆是' },
    sheet: '丁',
  }, {
    qid: '144',
    type: 'SELECT',
    statement: '造成中共經濟損失的主要根源為[  ]。',
    candidates: [{ NO: '1', content: '貪污' }, { NO: '2', content: '天災' }, { NO: '3', content: '戰亂' }],
    ans: { NO: '1', content: '貪污' },
    sheet: '丁',
  }, {
    qid: '145',
    type: 'SELECT',
    statement: '夜間突然出現之隱現目標，宜[  ]。',
    candidates: [{ NO: '1', content: '馬上攻擊' }, { NO: '2', content: '避眼1至2秒再行偵查' }, { NO: '3', content: '當作沒看到' }],
    ans: { NO: '2', content: '避眼1至2秒再行偵查' },
    sheet: '丁',
  }, {
    qid: '146',
    type: 'SELECT',
    statement: '通過砂石地時，應[  ]。',
    candidates: [{ NO: '1', content: '腳尖先著地' }, { NO: '2', content: '腳跟先著地' }, { NO: '3', content: '腳尖腳跟同時著地' }],
    ans: { NO: '2', content: '腳跟先著地' },
    sheet: '丁',
  }, {
    qid: '147',
    type: 'SELECT',
    statement: '目標偵查要領為[  ]。',
    candidates: [{ NO: '1', content: '概略偵查法' }, { NO: '2', content: '逐段偵查法' }, { NO: '3', content: '以上皆是' }],
    ans: { NO: '3', content: '以上皆是' },
    sheet: '丁',
  }, {
    qid: '148',
    type: 'SELECT',
    statement: '三人行進時，行進方式為[  ]。',
    candidates: [{ NO: '1', content: '在右' }, { NO: '2', content: '在左' }, { NO: '3', content: '一路(成行)' }],
    ans: { NO: '3', content: '一路(成行)' },
    sheet: '丁',
  }, {
    qid: '149',
    type: 'SELECT',
    statement: '[  ]，以上何種射擊姿勢，是用於深草或向下地形。',
    candidates: [{ NO: '1', content: '立姿' }, { NO: '2', content: '坐姿' }, { NO: '3', content: '臥姿' }],
    ans: { NO: '2', content: '坐姿' },
    sheet: '丁',
  }, {
    qid: '150',
    type: 'SELECT',
    statement: '共軍針對美軍航母進入黃海所舉行的演習，多在[  ]舉行',
    candidates: [{ NO: '1', content: '陸上' }, { NO: '2', content: '海上' }, { NO: '3', content: '空中' }],
    ans: { NO: '2', content: '海上' },
    sheet: '丁',
  }, {
    qid: '151',
    type: 'SELECT',
    statement: '下列何者不是變換射擊位置的時機?',
    candidates: [{ NO: '1', content: '伍班長命令時' }, { NO: '2', content: '敵火間斷時' }, { NO: '3', content: '敵火猛烈時' }],
    ans: { NO: '3', content: '敵火猛烈時' },
    sheet: '丁',
  }, {
    qid: '152',
    type: 'SELECT',
    statement: '在前進中，有射擊任務時[  ]。',
    candidates: [{ NO: '1', content: '應即射擊位置' }, { NO: '2', content: '迅速掩蔽' }, { NO: '3', content: '逃避' }],
    ans: { NO: '1', content: '應即射擊位置' },
    sheet: '丁',
  }, {
    qid: '153',
    type: 'SELECT',
    statement: '無故離去或不就職役逾6日者，處[  ]年以下有期徒刑。',
    candidates: [{ NO: '1', content: '二' }, { NO: '2', content: '三' }, { NO: '3', content: '四' }],
    ans: { NO: '2', content: '三' },
    sheet: '丁',
  }, {
    qid: '154',
    type: 'SELECT',
    statement: '仰臥起坐在鍛鍊[  ]肌肉。',
    candidates: [{ NO: '1', content: '腰部' }, { NO: '2', content: '胸部' }, { NO: '3', content: '腿部' }],
    ans: { NO: '1', content: '腰部' },
    sheet: '丁',
  }, {
    qid: '155',
    type: 'SELECT',
    statement: '聞「驗槍」，將槍斜舉胸前[  ]。',
    candidates: [{ NO: '1', content: '三十度' }, { NO: '2', content: '四十五度' }, { NO: '3', content: '六十度' }],
    ans: { NO: '2', content: '四十五度' },
    sheet: '丁',
  }, {
    qid: '156',
    type: 'SELECT',
    statement: '無線電在基本上[  ]保密的',
    candidates: [{ NO: '1', content: '是' }, { NO: '2', content: '不是' }],
    ans: { NO: '2', content: '不是' },
    sheet: '丁',
  }, {
    qid: '157',
    type: 'SELECT',
    statement: '山頂依形狀可分為[  ]。',
    candidates: [{ NO: '1', content: '平頂' }, { NO: '2', content: '尖頂' }, { NO: '3', content: '以上皆是' }],
    ans: { NO: '3', content: '以上皆是' },
    sheet: '丁',
  }, {
    qid: '158',
    type: 'SELECT',
    statement: '在近戰中距離25公尺內，或突擊最後階段，可採何種射擊姿勢?',
    candidates: [{ NO: '1', content: '腰射' }, { NO: '2', content: '肩射' }, { NO: '3', content: '刺射' }],
    ans: { NO: '1', content: '腰射' },
    sheet: '丁',
  }, {
    qid: '159',
    type: 'SELECT',
    statement: '鐵絲網的形式有[  ]。',
    candidates: [{ NO: '1', content: '屋頂型' }, { NO: '2', content: '四線式' }, { NO: '3', content: '以上皆是' }],
    ans: { NO: '3', content: '以上皆是' },
    sheet: '丁',
  }, {
    qid: '160',
    type: 'SELECT',
    statement: '3000公尺徒手跑步要領，上體姿勢應[  ]。',
    candidates: [{ NO: '1', content: '垂直' }, { NO: '2', content: '稍向前傾' }, { NO: '3', content: '稍向後傾' }],
    ans: { NO: '2', content: '稍向前傾' },
    sheet: '丁',
  },

  // 戊卷

  {
    qid: '161',
    type: 'YN',
    statement: '為防止防護面具遺失，宜在面具上書寫姓名或做上記號。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '戊',
  }, {
    qid: '162',
    type: 'YN',
    statement: '皮膚感到異常的刺激是生物戰劑攻擊之癥候。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '戊',
  }, {
    qid: '163',
    type: 'YN',
    statement: '上、下靶台時一律採端槍姿勢。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '戊',
  }, {
    qid: '164',
    type: 'YN',
    statement: '逃亡不超過三日並不犯罪，頂多行政處分(禁閉)。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '戊',
  }, {
    qid: '165',
    type: 'YN',
    statement: '防治敵人陰謀破壞第一要著，便是提高警覺。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '戊',
  }, {
    qid: '166',
    type: 'YN',
    statement: '地圖上水田是以綠色為表示。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '戊',
  }, {
    qid: '167',
    type: 'YN',
    statement: '偽裝原則以不妨礙任務之執行，適切選用偽裝材料。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '戊',
  }, {
    qid: '168',
    type: 'YN',
    statement: '愛民要成之於觀念，見諸於行動，實踐於紀律。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '戊',
  }, {
    qid: '169',
    type: 'YN',
    statement: '夜間障礙物破壞後不需加以標示。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '戊',
  }, {
    qid: '170',
    type: 'YN',
    statement: '雙方提物品行進時，遇長官約八步距離，即擺頭注目並問好。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '戊',
  }, {
    qid: '171',
    type: 'YN',
    statement: '掩護的要領之一，是上級掩護下級。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '戊',
  }, {
    qid: '172',
    type: 'YN',
    statement: '稜線包括地形稜線與軍事稜線部分。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '戊',
  }, {
    qid: '173',
    type: 'YN',
    statement: '碉堡對敵曲射武器之攻擊掩蔽效果最佳。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '戊',
  }, {
    qid: '174',
    type: 'YN',
    statement: '肛溫攝氏溫度四十二度以上，無汗、意識模糊時須立即急救。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '戊',
  }, {
    qid: '175',
    type: 'YN',
    statement: '工事位置選定要領，首在發揚火力，次求掩蔽身體。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '戊',
  }, {
    qid: '176',
    type: 'YN',
    statement: '射擊完畢後，應將彈殼與實彈分開呈繳。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '戊',
  }, {
    qid: '177',
    type: 'YN',
    statement: '對敵核子爆炸的處置是立即閉雙眼，面相炸點。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: false },
    sheet: '戊',
  }, {
    qid: '178',
    type: 'YN',
    statement: '深草可以隱蔽，如循直線通過，最易暴露目標。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '戊',
  }, {
    qid: '179',
    type: 'YN',
    statement: '單人立射散兵坑可分為開置式及半掩蓋式。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '戊',
  }, {
    qid: '180',
    type: 'YN',
    statement: '夜間因觀測不易，易生恐懼心理，而常引起猜疑及驚悸。',
    candidates: [{ content: true }, { content: false }],
    ans: { content: true },
    sheet: '戊',
  }, {
    qid: '181',
    type: 'SELECT',
    statement: '肩槍時，槍身垂直身體右側，距身體約[  ]。',
    candidates: [{ NO: '1', content: '五公分' }, { NO: '2', content: '十公分' }, { NO: '3', content: '十五公分' }],
    ans: { NO: '2', content: '十公分' },
    sheet: '戊',
  }, {
    qid: '182',
    type: 'SELECT',
    statement: '斷牆通過的方式有[  ]。',
    candidates: [{ NO: '1', content: '架設繩梯攀登' }, { NO: '2', content: '攀高通過' }, { NO: '3', content: '以上皆是' }],
    ans: { NO: '3', content: '以上皆是' },
    sheet: '戊',
  }, {
    qid: '183',
    type: 'SELECT',
    statement: '二人行進遇高階人員時，由[  ]發「敬禮」、「禮畢」口令。',
    candidates: [{ NO: '1', content: '左邊' }, { NO: '2', content: '右邊' }, { NO: '3', content: '同時' }],
    ans: { NO: '2', content: '右邊' },
    sheet: '戊',
  }, {
    qid: '184',
    type: 'SELECT',
    statement: '下列何者為前進時機要領?',
    candidates: [{ NO: '1', content: '敵火間斷時' }, { NO: '2', content: '狀況許可時' }, { NO: '3', content: '以上皆是' }],
    ans: { NO: '3', content: '以上皆是' },
    sheet: '戊',
  }, {
    qid: '185',
    type: 'SELECT',
    statement: '敵核子爆炸後約停[  ]秒鐘，主動納入伍、班掌握繼續戰鬥。',
    candidates: [{ NO: '1', content: '三十' }, { NO: '2', content: '六十' }, { NO: '3', content: '九十' }],
    ans: { NO: '3', content: '九十' },
    sheet: '戊',
  }, {
    qid: '186',
    type: 'SELECT',
    statement: '練習投遠及投準最好的方法為[  ]。',
    candidates: [{ NO: '1', content: '立投' }, { NO: '2', content: '跳投' }, { NO: '3', content: '跑投' }],
    ans: { NO: '3', content: '跑投' },
    sheet: '戊',
  }, {
    qid: '187',
    type: 'SELECT',
    statement: '止血帶止血法運用於臂及手部，可縛於腋窩下[  ]。',
    candidates: [{ NO: '1', content: '五公分' }, { NO: '2', content: '十公分' }, { NO: '3', content: '十五公分' }],
    ans: { NO: '2', content: '十公分' },
    sheet: '戊',
  }, {
    qid: '188',
    type: 'SELECT',
    statement: '國造六五K2步槍的長度為?',
    candidates: [{ NO: '1', content: '100公分' }, { NO: '2', content: '101公分' }, { NO: '3', content: '102公分' }],
    ans: { NO: '2', content: '101公分' },
    sheet: '戊',
  }, {
    qid: '189',
    type: 'SELECT',
    statement: '陡峻之高地與谷地交錯的地帶稱為[  ]。',
    candidates: [{ NO: '1', content: '山地' }, { NO: '2', content: '高地' }, { NO: '3', content: '丘陵地' }],
    ans: { NO: '1', content: '山地' },
    sheet: '戊',
  }, {
    qid: '190',
    type: 'SELECT',
    statement: '聞立正口令時腳尖向外分開[  ]。',
    candidates: [{ NO: '1', content: '四十度' }, { NO: '2', content: '六十度' }, { NO: '3', content: '四十五度' }],
    ans: { NO: '3', content: '四十五度' },
    sheet: '戊',
  }, {
    qid: '191',
    type: 'SELECT',
    statement: '在戰場上單兵最常用的狀況報告方法為[  ]。',
    candidates: [{ NO: '1', content: '口頭報告' }, { NO: '2', content: '書面報告' }, { NO: '3', content: '要圖報告' }],
    ans: { NO: '1', content: '口頭報告' },
    sheet: '戊',
  }, {
    qid: '192',
    type: 'SELECT',
    statement: '迴旋以兩腳掌為軸，向左後方旋轉[  ]。',
    candidates: [{ NO: '1', content: '90度' }, { NO: '2', content: '180度' }, { NO: '3', content: '360度' }],
    ans: { NO: '2', content: '180度' },
    sheet: '戊',
  }, {
    qid: '193',
    type: 'SELECT',
    statement: '等高線毫無規則，表示該處地形[  ]。',
    candidates: [{ NO: '1', content: '平整' }, { NO: '2', content: '崎嶇不平' }, { NO: '3', content: '以上皆非' }],
    ans: { NO: '2', content: '崎嶇不平' },
    sheet: '戊',
  }, {
    qid: '194',
    type: 'SELECT',
    statement: '三人行進時，行進方式為[  ]。',
    candidates: [{ NO: '1', content: '在右' }, { NO: '2', content: '在左' }, { NO: '3', content: '一路(成行)' }],
    ans: { NO: '3', content: '一路(成行)' },
    sheet: '戊',
  }, {
    qid: '195',
    type: 'SELECT',
    statement: '團體跑步時，步伐要求一致，步幅約[  ]為宜。',
    candidates: [{ NO: '1', content: '100公分' }, { NO: '2', content: '110公分' }, { NO: '3', content: '公分' }],
    ans: { NO: '1', content: '100公分' },
    sheet: '戊',
  }, {
    qid: '196',
    type: 'SELECT',
    statement: '扣引步槍板機[  ]。',
    candidates: [{ NO: '1', content: '不知不覺擊發' }, { NO: '2', content: '猛扣而擊發' }, { NO: '3', content: '擊扣而擊發' }],
    ans: { NO: '1', content: '不知不覺擊發' },
    sheet: '戊',
  }, {
    qid: '197',
    type: 'SELECT',
    statement: '變換射擊位置的要領為[  ]。',
    candidates: [{ NO: '1', content: '敵或間斷時' }, { NO: '2', content: '鄰兵妨礙射擊時' }, { NO: '3', content: '以上皆是' }],
    ans: { NO: '3', content: '以上皆是' },
    sheet: '戊',
  }, {
    qid: '198',
    type: 'SELECT',
    statement: '仰臥起坐，男性合格標準為1分鐘[  ]。',
    candidates: [{ NO: '1', content: '二十下' }, { NO: '2', content: '依年齡計算' }, { NO: '3', content: '三十下' }],
    ans: { NO: '2', content: '依年齡計算' },
    sheet: '戊',
  }, {
    qid: '199',
    type: 'SELECT',
    statement: '因為大量流汗造成脫水和體內鹽分分配失調所引起的是[  ]。',
    candidates: [{ NO: '1', content: '熱中暑' }, { NO: '2', content: '熱衰竭' }, { NO: '3', content: '熱痙攣' }],
    ans: { NO: '3', content: '熱痙攣' },
    sheet: '戊',
  }, {
    qid: '200',
    type: 'SELECT',
    statement: '地形地物利用原則，射擊位置選擇，通常利用[  ]。',
    candidates: [{ NO: '1', content: '中間' }, { NO: '2', content: '右側' }, { NO: '3', content: '左側' }],
    ans: { NO: '2', content: '右側' },
    sheet: '戊',
  },

]